// UserManagement.ReactClient/src/components/user/adduser.component.jsx
import React, { useEffect, useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { UserService } from "../../services/user.service";
import { AuthService } from "../../services/auth.service";
import { UserModel } from "../../models/user.model";
import { useNavigate } from "react-router-dom";
import { insertUser, userAction } from "../../store/user.slice";
import { useForm } from "react-hook-form";

function AddUser() {
  const {
    register,
    handleSubmit,
    formState: {
      touchedFields,
      isDirty,
      isValid,
      dirtyFields,
      isSubmitted,
      errors,
    },
    watch,
  } = useForm();
  // const onSubmit = (data) => console.log(data);
  const status = useSelector((state) => state.users.status);
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(userAction.resetStatus());
  }, [dispatch]);

  // const [formData, setFormData] = useState({
  //   name: "",
  //   username: "",
  //   email: "",
  //   role: "",
  // });

  //Handle form submission
  const onSubmit = (formData) => {
    // Dispatch submitForm action with form data
    const userService = new UserService();
    const authService = new AuthService();
    var user = new UserModel(
      formData.username,
      formData.name,
      formData.email,
      formData.role,
      authService.getUserName()
    );
    dispatch(insertUser({ user, userService }));
  };
  const navigate = useNavigate();
  useEffect(() => {
    if (status == "succeededAdd") {
      navigate("/");
    }
  }, [status]);

  return (
    <div className="container">
      <div className="row justify-content-center">
        <div className="col-md-6">
          <div className="card mt-5">
            <div className="card-body">
              {status == "loading" && <p>....Loading</p>}
              {status == "failed" && <p>An error occurred</p>}
              {status == null && (
                <div>
                  <h5 className="card-title text-center">New User</h5>
                  <form onSubmit={handleSubmit(onSubmit)}>
                    <div className="mb-3">
                      <label htmlFor="name" className="form-label">
                        Name
                      </label>
                      <input
                        type="text"
                        className={
                          errors.name
                            ? "form-control error-field"
                            : "form-control"
                        }
                        {...register("name", { required: true, maxLength: 50 })}
                      />
                    </div>
                    <div className="mb-3">
                      <label htmlFor="username" className="form-label">
                        User Name
                      </label>
                      <input
                        type="text"
                        className={
                          errors.username
                            ? "form-control error-field"
                            : "form-control"
                        }
                        {...register("username", {
                          required: true,
                          maxLength: 50,
                        })}
                      />
                    </div>
                    <div className="mb-3">
                      <label htmlFor="email" className="form-label">
                        Email
                      </label>
                      <input
                        type="email"
                        className={
                          errors.email
                            ? "form-control error-field"
                            : "form-control"
                        }
                        {...register("email", {
                          required: true,
                          pattern: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                        })}
                      />
                    </div>
                    <div className="mb-3">
                      <label htmlFor="Role" className="form-label">
                        Role
                      </label>
                      <select
                        className={
                          errors.role
                            ? "form-control error-field"
                            : "form-control"
                        }
                        {...register("role", { required: true })}
                      >
                        <option value="">Select Role</option>
                        <option value="Admin">Admin</option>
                        <option value="User">User</option>
                      </select>
                    </div>
                    <button type="submit" className="btn btn-primary w-100">
                      Submit
                    </button>
                  </form>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
export default AddUser;

// UserManagement.Client/src/app/components/adduser/adduser.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { CommonModule } from '@angular/common';
import UserModel from '../../models/user.model';
import { AuthService } from '../../services/auth.service';
import { UserService } from '../../services/user.service';
import { Router } from '@angular/router';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { LanguageService } from '../../services/language.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-adduser',
  standalone: true,
  imports: [FormsModule,CommonModule,TranslateModule],
  templateUrl: './adduser.component.html',
  styleUrl: './adduser.component.css'
})
export class AdduserComponent implements OnInit,OnDestroy {
  formSubmitted:boolean=false;
  private subscription: Subscription;
  
  constructor(private authService:AuthService,private userService:UserService,private router:Router,
    private languageService:LanguageService){}

  ngOnInit(): void {
    this.languageService.setInitialAppLanguage();
  }
  onSubmit(addUserForm:NgForm){
    this.formSubmitted = true;
    if(addUserForm.valid)
      {
          let actionUser:string = this.authService.getUserName();
          let addUserObj = new UserModel(addUserForm.value.name,addUserForm.value.username,addUserForm.value.email,addUserForm.value.role,actionUser);
          this.subscription = this.userService.addUser(addUserObj).subscribe(
            () => { this.router.navigate(['userlist'])},
            (err) => {console.log(err);}
          );
      }

    console.log(addUserForm);
  }
  ngOnDestroy(): void {
    if(this.subscription){
      this.subscription.unsubscribe();
    }
  }
}

<div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mt-5">
          <div class="card-body">
            <h5 class="card-title text-center">{{'New User'|translate}}</h5>
            <form (ngSubmit)="onSubmit(addUserForm)" #addUserForm="ngForm">
                <div class="mb-3">
                    <label for="name" class="form-label">{{'Name'|translate}}</label>
                    <input type="text" name="name"
                     class="form-control"
                     [ngClass]="{ 'is-invalid': nameCtrl.invalid && (nameCtrl.touched || formSubmitted)}" 
                     id="username" required #nameCtrl="ngModel" ngModel>
                  </div>
              <div class="mb-3">
                <label for="username" class="form-label">{{'User Name'|translate}}</label>
                <input type="text" name="username"
                 class="form-control"
                 [ngClass]="{ 'is-invalid': usernameCtrl.invalid && (usernameCtrl.touched || formSubmitted)}" 
                 id="username" required #usernameCtrl="ngModel" ngModel>
              </div>
              <div class="mb-3">
                <label for="email" class="form-label">{{'Email'|translate}}</label>
                <input type="email" name="email"
                 class="form-control" 
                 [ngClass]="{ 'is-invalid': emailCtrl.invalid && (emailCtrl.touched || formSubmitted)}"
                 id="email" required #emailCtrl="ngModel" email ngModel>
              </div>
              <div class="mb-3">
                <label for="Role" class="form-label">{{'Role'|translate}}</label>
                <select name="role" class="form-control"
                [ngClass]="{ 'is-invalid': roleCtrl.invalid && (roleCtrl.touched || formSubmitted)}"
                #roleCtrl="ngModel" ngModel required 
                >
                    <option value="">{{'Select Role'|translate}}</option>
                    <option value="Admin">{{'Admin'|translate}}</option>
                    <option value="User">{{'User'|translate}}</option>
                </select>
              </div>
              <button type="submit" class="btn btn-primary w-100">{{'Submit'|translate}}</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
