// UserManagement.ReactClient/src/components/user/edituser.component.jsx
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useParams } from "react-router-dom";
import { updateUser } from "../../store/user.slice";
import { AuthService } from "../../services/auth.service";
import { UserService } from "../../services/user.service";
import { useNavigate } from "react-router-dom";
import { UserModel } from "../../models/user.model";
import { useForm } from "react-hook-form";

function EditUser() {
  const { id } = useParams();
  const dispatch = useDispatch();

  const { status, userListObj } = useSelector((state) => state.users);

  const {
    register,
    handleSubmit,
    reset,
    formState: {
      touchedFields,
      isDirty,
      isValid,
      dirtyFields,
      isSubmitted,
      errors,
    },
    watch,
  } = useForm();

  // Handle form submission
  const editUserForm = (formData) => {
    //e.preventDefault();
    // Dispatch submitForm action with form data
    const userService = new UserService();
    const authService = new AuthService();
    var user = new UserModel(
      formData.username,
      formData.name,
      formData.email,
      formData.role,
      authService.getUserName()
    );
    dispatch(updateUser({ user, userService }));
  };

  useEffect(() => {
    if (userListObj.data != null) {
      const userObj = userListObj.data.filter((user) => user.id == id)[0];
      if (userObj != null) {
        reset({
          name: userObj.name,
          username: userObj.username,
          email: userObj.email,
          role: userObj.role,
        });
      }
    }
  }, [userListObj]);
  const navigate = useNavigate();
  useEffect(() => {
    if (status == "succeededEdit") {
      navigate("/");
    }
  }, [status]);

  return (
    <>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="card mt-5">
              <div class="card-body">
                <h5 class="card-title text-center">Edit User</h5>
                <form onSubmit={handleSubmit(editUserForm)}>
                  <div class="mb-3">
                    <label for="name" class="form-label">
                      Name
                    </label>
                    <input
                      type="text"
                      className={
                        errors.name
                          ? "form-control error-field"
                          : "form-control"
                      }
                      {...register("name", { required: true, maxLength: 50 })}
                    />
                  </div>
                  <div class="mb-3">
                    <label for="username" class="form-label">
                      User Name
                    </label>
                    <input
                      type="text"
                      className={
                        errors.username
                          ? "form-control error-field"
                          : "form-control"
                      }
                      {...register("username", {
                        required: true,
                        maxLength: 50,
                      })}
                    />
                  </div>
                  <div class="mb-3">
                    <label for="email" class="form-label">
                      Email
                    </label>
                    <input
                      type="email"
                      className={
                        errors.email
                          ? "form-control error-field"
                          : "form-control"
                      }
                      {...register("email", {
                        required: true,
                        pattern: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                      })}
                    />
                  </div>
                  <div class="mb-3">
                    <label for="Role" class="form-label">
                      Role
                    </label>
                    <select
                      className={
                        errors.role
                          ? "form-control error-field"
                          : "form-control"
                      }
                      {...register("role", { required: true })}
                    >
                      <option value="">Select Role</option>
                      <option value="Admin">Admin</option>
                      <option value="User">User</option>
                    </select>
                  </div>
                  <button type="submit" class="btn btn-primary w-100">
                    Submit
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default EditUser;

// UserManagement.Client/src/app/components/edituser/edituser.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import UserModel from '../../models/user.model';
import { UserService } from '../../services/user.service';
import { FormsModule, NgForm } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { CommonModule } from '@angular/common';
import { LanguageService } from '../../services/language.service';
import { TranslateModule } from '@ngx-translate/core';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-edituser',
  standalone: true,
  imports: [FormsModule,CommonModule,TranslateModule],
  templateUrl: './edituser.component.html',
  styleUrl: './edituser.component.css'
})
export class EdituserComponent implements OnInit,OnDestroy {
  formSubmitted:boolean=false;
  id: string | null = null;
  user:any =null;
  email:string = "";
  username:string = "";
  name:string = ""
  role:string = "";
  private subscription: Subscription;
  private subimtSubscription: Subscription;
  
  constructor(private route:ActivatedRoute,private userService:UserService,
    private authService:AuthService,private router:Router,private languageService:LanguageService){}
  ngOnInit(){
    this.languageService.setInitialAppLanguage();
    this.route.paramMap.subscribe(params => {
      this.id = params.get('id');
      this.getUserForEdit(this.id);
    });
  }
    getUserForEdit(id:string|null){
      this.subscription = this.userService.getUser(id).subscribe(
        (res) => 
        { 
          this.user = res;console.log(res)
          this.username = res.username;
          this.email = res.email;
          this.role = res.role;
          this.name = res.name;
        },
        (err) => {console.log(err);}
      );
    }
    onSubmit(ngForm:NgForm)
    {
      this.formSubmitted = true;
      let actionUser:string = this.authService.getUserName();
      let eidtUserObj = new UserModel(this.name,this.username,this.email,this.role,actionUser);
      this.subimtSubscription = this.userService.updateUser(eidtUserObj).subscribe(
        (res) =>{this.router.navigate(['userlist'])},
        (error) => {console.log(error)}
      )
    }
    ngOnDestroy(): void {
      if(this.subscription)
      {
        this.subscription.unsubscribe();
      }
      if(this.subimtSubscription)
      {
        this.subimtSubscription.unsubscribe();
      }
    }
}

<div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mt-5">
          <div class="card-body">
            <h5 class="card-title text-center">{{'Edit User'|translate}}</h5>
            <form (ngSubmit)="onSubmit(editUserForm)" #editUserForm="ngForm">
                <div class="mb-3">
                    <label for="name" class="form-label">{{'Name'|translate}}</label>
                    <input type="text" name="name"
                     class="form-control"
                     [ngClass]="{ 'is-invalid': nameCtrl.invalid && (nameCtrl.touched || formSubmitted)}" 
                     id="username" required #nameCtrl="ngModel" [(ngModel)]="name">
                  </div>
              <div class="mb-3">
                <label for="username" class="form-label">{{'User Name'|translate}}</label>
                <input type="text" name="username"
                 class="form-control"
                 [disabled]="true" value="{{username}}"
                 id="username"  #usernameCtrl="ngModel" ngModel>
              </div>
              <div class="mb-3">
                <label for="email" class="form-label">{{'Email'|translate}}</label>
                <input type="email" name="email"
                 class="form-control" 
                 [ngClass]="{ 'is-invalid': emailCtrl.invalid && (emailCtrl.touched || formSubmitted)}"
                 id="email" required #emailCtrl="ngModel" email [(ngModel)]="email">
              </div>
              <div class="mb-3">
                <label for="Role" class="form-label">{{'Role'|translate}}</label>
                <select name="role" class="form-control"
                [ngClass]="{ 'is-invalid': roleCtrl.invalid && (roleCtrl.touched || formSubmitted)}"
                #roleCtrl="ngModel" [(ngModel)]="role" required 
                >
                    <option value="">{{'Select Role'|translate}}</option>
                    <option value="Admin">{{'Admin'|translate}}</option>
                    <option value="User">{{'User'|translate}}</option>
                </select>
              </div>
              <button type="submit" class="btn btn-primary w-100">{{'Submit'|translate}}</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
