// UserManagement.Client/src/app/components/login/login.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { FormsModule, NgForm } from '@angular/forms';
import { CommonModule } from '@angular/common';
import LoginModel from '../../models/login.model';
import { Router } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';
import { LanguageService } from '../../services/language.service';
import { Subscription } from 'rxjs';


@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule,CommonModule,TranslateModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class LoginComponent implements OnInit,OnDestroy {
  formSubmitted:boolean=false;
  formError:string="";
  private subscription: Subscription;
  constructor(private authService:AuthService,private router:Router,private languageService:LanguageService){

  }
  ngOnInit(): void {
    this.languageService.setInitialAppLanguage();
    if(this.authService.isLoggedIn())
      {
        this.router.navigate(['userlist']);
      }
  }
  onSubmitLogin(loginForm:NgForm)
  {
      this.formSubmitted = true;
      if(loginForm.valid)
      {
          let loginObj = new LoginModel(loginForm.value.username,loginForm.value.password);
          this.subscription = this.authService.login(loginObj).subscribe(
            () => { this.router.navigate(['userlist'])},
            (err) => {console.log(err);this.formError=err.error;}
          );
      }
      console.log(loginForm);
  }
  ngOnDestroy(): void {
    if(this.subscription)
      {
        this.subscription.unsubscribe();
      }
  }
}

<div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mt-5">
          <div class="card-body">
            <h5 class="card-title text-center">{{'Login'|translate}}</h5>
            <form (ngSubmit)="onSubmitLogin(loginForm)" #loginForm="ngForm">
              <div class="mb-3">
                <label for="username" class="form-label">{{'User Name'|translate}}</label>
                <input type="text" name="username"
                 class="form-control"
                 [ngClass]="{ 'is-invalid': usernameCtrl.invalid && (usernameCtrl.touched || formSubmitted)}" 
                 id="username" required #usernameCtrl="ngModel" ngModel>
              </div>
              <div class="mb-3">
                <label for="password" class="form-label">{{'Password'|translate}}</label>
                <input type="password" name="password"
                 class="form-control" 
                 [ngClass]="{ 'is-invalid': passwordCtrl.invalid && (passwordCtrl.touched || formSubmitted)}"
                 id="password" required #passwordCtrl="ngModel" ngModel>
                 <div class="alert alert-danger" *ngIf="formError != ''">{{formError}}</div>
              </div>
              <button type="submit" class="btn btn-primary w-100">{{'Submit'|translate}}</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

// UserManagement.ReactClient/src/components/login/login.component.jsx
import { AuthService } from "../../services/auth.service";
import { LoginModel } from "../../models/LoginModel";
import { useNavigate } from "react-router-dom";
import { useState } from "react";

function Login() {
  const navigate = useNavigate();
  const [loginData, setloginData] = useState({
    username: "",
    password: "",
  });
  const onSubmitLogin = async (e) => {
    e.preventDefault();
    try {
      const authService = new AuthService();
      var response = await authService.login(
        new LoginModel(loginData.username, loginData.password)
      );
      if (response.data.token) {
        navigate("/");
      }
    } catch (error) {
      console.error("Error submitting form:", error);
    }
  };
  const handleChange = (e) => {
    const { name, value } = e.target;
    setloginData({
      ...loginData,
      [name]: value,
    });
  };

  return (
    <>
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-md-6">
            <div className="card mt-5">
              <div className="card-body">
                <h5 className="card-title text-center">Login</h5>
                <form onSubmit={onSubmitLogin}>
                  <div className="mb-3">
                    <label htmlFor="username" className="form-label">
                      User Name
                    </label>
                    <input
                      type="text"
                      name="username"
                      className="form-control"
                      id="username"
                      value={loginData.userName}
                      onChange={handleChange}
                      required
                    />
                  </div>
                  <div className="mb-3">
                    <label htmlFor="password" className="form-label">
                      Password
                    </label>
                    <input
                      type="password"
                      name="password"
                      className="form-control"
                      id="password"
                      value={loginData.password}
                      onChange={handleChange}
                      required
                    />
                    {/* <div className="alert alert-danger" *ngIf="formError != ''">{{formError}}</div> */}
                  </div>
                  <button type="submit" className="btn btn-primary w-100">
                    Submit
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export default Login;
